In [8]:
from transcription_pipeline.RateExtraction import AverageAndFit
import pandas as pd
import matplotlib as mpl
mpl.use('TkAgg')

In [9]:
dataset_folder = '/mnt/Data1/Nick/transcription_pipeline/'


embryo_datasets = {
    # 22C embryos Var2, 0.230 um/pixel
    '001': [
        'test_data/NSPARC/2025-05-28/MCP-mSG_His-RFP_RBS(001)_embryo01',
        'test_data/NSPARC/2025-05-28/MCP-mSG_His-RFP_RBS(001)_embryo02',
        'test_data/NSPARC/2025-05-28/MCP-mSG_His-RFP_RBS(001)_embryo03',
        'test_data/NSPARC/2025-05-28/MCP-mSG_His-RFP_RBS(001)_embryo04',
    ],

    # 22C embryos PWM, 0.230 um/pixel
    '003': [
        'test_data/NSPARC/2025-05-27/MCP-mSG_His-RFP_RBS(003)_embryo02',
        'test_data/NSPARC/2025-05-29/MCP-mSG_His-RFP_RBS(003)_embryo01',
        'test_data/NSPARC/2025-05-29/MCP-mSG_His-RFP_RBS(003)_embryo02',
    ],
}

test_dataset_name = dataset_folder + embryo_datasets['003'][2]
print('Dataset Path: ' + test_dataset_name)

Dataset Path: /mnt/Data1/Nick/transcription_pipeline/test_data/NSPARC/2025-05-29/MCP-mSG_His-RFP_RBS(003)_embryo02

In [10]:
# Specify here at what frame NC14 starts
nc14_start_frame = 0

# Width of averaging window for time bins
time_bin_width = 2

# Number of bins you want to split the full embryo into
num_bins = 40

# Load in compiled dataframe
dataframe_path = test_dataset_name + '/compiled_dataframe.pkl'
compiled_dataframe = pd.read_pickle(dataframe_path)

In [11]:
compiled_dataframe.head()

,particle,frame,t_s,intensity_from_neighborhood,intensity_std_error_from_neighborhood,x,y,ap,ap90
0,2,"[225, 226, 227, 228, 229, 230, 231, 232, 233, ...","[460.05177960000003, 462.0748435999993, 464.09...","[78.95077685950415, 129.640632, 55.21568852459...","[17.834635455964374, 16.411708660848692, 15.43...","[543.2168151111881, 542.7223457203268, 543.786...","[57.78055240220686, 56.18082713754482, 56.3010...","[0.342000225032329, 0.34226199127546414, 0.341...","[-0.05601296163026239, -0.057672990114523925, ..."
1,3,"[97, 98, 99, 100, 101, 102, 103, 104, 105, 106...","[200.9334196000006, 202.78251559999958, 204.97...","[28.725166666666667, 34.444194915254236, 50.91...","[14.387986693187248, 13.963850183555875, 14.80...","[801.9887361108551, 803.1480386066471, 803.894...","[111.51922524633602, 110.94007609904827, 110.8...","[0.2326566534916065, 0.23219572597519983, 0.23...","[-0.02218160993194913, -0.022903804599406646, ..."
2,4,"[25, 26, 28, 30, 33, 34, 35, 36, 37, 38, 39, 4...","[53.8633406000007, 56.75635859999992, 60.80228...","[21.849209677419353, 48.24290677966102, 42.867...","[14.415952525816213, 15.440625214869703, 13.89...","[751.0487845377513, 752.1482985318606, 753.664...","[14.778626981178814, 13.214655680657806, 13.02...","[0.25722180894969254, 0.2568204602669374, 0.25...","[-0.12066350656930948, -0.12242980264199937, -..."
3,5,"[114, 115, 116, 117, 118, 119, 120, 121, 122, ...","[233.7365116000008, 237.6955485999994, 239.544...","[50.05210569105691, 123.7297890625, 136.876126...","[14.008477980568676, 18.509445237893743, 17.92...","[839.4836727091124, 840.7732836675456, 840.254...","[16.0418604576817, 26.86392176099205, 26.24617...","[0.22045732850335417, 0.21953995605753257, 0.2...","[-0.12732701522511772, -0.11591083944439584, -..."
4,6,"[370, 375, 379, 380, 381, 386, 387, 389, 390, ...","[753.5610636, 763.8501366000008, 770.006130599...","[31.85696428571429, 44.356339999999996, 14.283...","[16.081181860940536, 17.28634182250253, 17.179...","[806.6567299996558, 787.4005140672989, 786.941...","[168.79316566483746, 159.29948900323836, 166.1...","[0.22869726575407795, 0.23702784790045983, 0.2...","[0.038431950339986705, 0.030058694314182413, 0..."

In [12]:
aafdata = AverageAndFit(compiled_dataframe, nc14_start_frame, time_bin_width, num_bins, test_dataset_name)

No previous bin fit checking results detected. Do bin fitting for the dataframe.

/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1051: RuntimeWarning: Mean of empty slice.
  time_bin_means = np.array([intensity_flat[time_bin_indices == i].mean() for i in range(1, len(time_bins))])
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1091: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_centers'][bin] = time_bin_centers
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1091: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['time_bin_centers'][bin] = time_bin_centers
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1092: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_means'][bin] = time_bin_means
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1092: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['time_bin_means'][bin] = time_bin_means
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1093: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_stddevs'][bin] = time_bin_stddevs
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1093: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Failed to fit average trace 18: Each lower bound must be strictly less than each upper bound.

/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1102: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_fit_result'][bin] = bin_fit_result
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_fit_result'][bin] = bin_fit_result
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1103: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_fit_slope'][bin] = bin_fit_result[4][3]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_fit_slope'][bin] = bin_fit_result[4][3]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1051: RuntimeWarning: Mean of empty slice.
  time_bin_means = np.array([intensity_flat[time_bin_indices == i].mean() for i in range(1, len(time_bins))])
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/mnt/Data1/Nick/miniforge3/envs/transcription_pipeline/lib/python3.10/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1091: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_centers'][bin] = time_bin_centers
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1091: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['time_bin_centers'][bin] = time_bin_centers
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1092: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_means'][bin] = time_bin_means
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1092: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['time_bin_means'][bin] = time_bin_means
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1093: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_stddevs'][bin] = time_bin_stddevs
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1093: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['time_bin_stddevs'][bin] = time_bin_stddevs
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1094: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['time_bin_stderrs'][bin] = time_bin_stderrs
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1094: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['time_bin_stderrs'][bin] = time_bin_stderrs
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1097: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['denoised_time_bin_means'][bin] = denoised_time_bin_means
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1097: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['denoised_time_bin_means'][bin] = denoised_time_bin_means
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1102: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_fit_result'][bin] = bin_fit_result
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_fit_result'][bin] = bin_fit_result
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1105: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1087: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.bin_average_fit_dataframe['bin_particle_number'][bin] = bin_particle_num[bin]
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  self.bin_average_fit_dataframe['approval_status'][bin] = -1
/mnt/Data1/Nick/transcription_pipeline/transcription_pipeline/RateExtraction.py:1107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [13]:
mpl.use('TkAgg')
aafdata.check_bin_fits()

Moved to bin 6 out of 40, the first unchecked bin

In [14]:
aafdata.save_checked_bin_fits()

Checked bin fits saved

In [15]:
# Load checked particle fits
fits_path = test_dataset_name + '/bin_fits_checked.pkl'
bin_fits_checked = pd.read_pickle(fits_path)

In [16]:
bin_fits_checked

,index,time_bin_centers,time_bin_means,time_bin_stddevs,time_bin_stderrs,denoised_time_bin_means,bin_fit_result,bin_fit_slope,bin_fit_result_modified,bin_fit_slope_modified,bin_particle_number,approval_status
0,0,None,None,None,None,None,None,NaN,None,NaN,0,-1
1,1,None,None,None,None,None,None,NaN,None,NaN,0,-1
2,2,None,None,None,None,None,None,NaN,None,NaN,0,-1
3,3,None,None,None,None,None,None,NaN,None,NaN,0,-1
4,4,None,None,None,None,None,None,NaN,None,NaN,0,-1
5,5,"[0.016666666666666666, 0.08333333333333333, 0....","[38.12565412317647, 58.385, 35.70246405919662,...","[14.227325376400804, 0.0, 5.483626849894295, 0...","[8.214150135913398, 0.0, 3.8775097310568816, 0...","[46.46117356469185, 46.58677403558213, 46.8838...","[[0.016666666666666666, 0.08333333333333333, 0...",43.386851,None,NaN,3,-1
6,6,"[0.016666666666666666, 0.05, 0.083333333333333...","[56.86893032999564, 41.37162692786626, 78.3142...","[58.12431195022625, 19.042114842167926, 102.46...","[12.392144945465205, 6.021645436774835, 34.156...","[71.56465799352684, 71.68306368567741, 71.9278...","[[0.016666666666666666, 0.05, 0.08333333333333...",64.928917,None,NaN,20,1
7,7,"[0.016666666666666666, 0.05, 0.083333333333333...","[49.95001593557454, 66.94568636782077, 48.6885...","[26.976183455503907, 33.5143998952928, 27.7494...","[4.626377295163675, 9.295222099144857, 6.73023...","[65.80603609562812, 65.90046055377343, 66.0887...","[[0.016666666666666666, 0.05, 0.08333333333333...",61.148686,None,NaN,32,1
8,8,"[0.016666666666666666, 0.05, 0.083333333333333...","[41.73553055412751, 74.98170704747211, 75.5044...","[29.77932135858564, 55.48013983143531, 69.5970...","[4.390721394075176, 10.880550600667114, 14.206...","[81.89182160596519, 82.01491040375957, 82.2621...","[[0.016666666666666666, 0.05, 0.08333333333333...",61.701873,"[[0.11666666666666667, 0.15, 0.183333333333333...",73.665263,43,2
9,9,"[0.016666666666666666, 0.05, 0.083333333333333...","[52.50466782969829, 89.50605327648563, 85.1819...","[49.78421814689565, 82.47267083070565, 83.1283...","[7.5052532761116035, 17.997012230804057, 16.62...","[96.56823862137853, 96.67332614346822, 96.8843...","[[0.016666666666666666, 0.05, 0.08333333333333...",66.791644,None,NaN,39,1
10,10,"[0.016666666666666666, 0.05, 0.083333333333333...","[48.52468144675837, 100.92809390115876, 93.163...","[39.50225968206991, 85.44321645126018, 72.2685...","[4.472750143482376, 17.088643290252037, 11.426...","[91.88766835083989, 91.96430141023222, 92.1156...","[[0.016666666666666666, 0.05, 0.08333333333333...",36.053166,None,NaN,67,1
11,11,"[0.016666666666666666, 0.05, 0.083333333333333...","[52.03291831544855, 94.21679790074336, 95.1805...","[44.40997927974001, 66.65828724143608, 65.0813...","[4.55636773575635, 10.410275479546348, 10.1639...","[95.06592360290412, 95.13058171927557, 95.2596...","[[0.016666666666666666, 0.05, 0.08333333333333...",39.208652,None,NaN,79,1
12,12,"[0.016666666666666666, 0.05, 0.083333333333333...","[42.81777114021682, 97.35431105883616, 99.3720...","[26.01230936154224, 82.82358717845578, 72.8255...","[3.25153867019278, 16.243041815719202, 12.6773...","[94.5057796306779, 94.55170101300348, 94.64659...","[[0.016666666666666666, 0.05, 0.08333333333333...",34.317179,None,NaN,57,1
13,13,"[0.016666666666666666, 0.05, 0.083333333333333...","[48.62719959664449, 70.65568075058168, 82.1363...","[30.649778145994983, 44.72965690056886, 47.460...","[3.831222268249373, 8.453110599153527, 9.68786...","[75.36376743444288, 75.4208619016471, 75.53526...","[[0.016666666666666666, 0.05, 0.08333333333333...",29.466408,None,NaN,57,1
14,14,"[0.016666666666666666, 0.05, 0.083333333333333...","[47.091503153311194, 89.26575337745724, 84.475...","[33.28351038321167, 54.12560743873575, 54.0335...","[4.571841756430002, 12.417265951747497, 10.596...","[79.04663879785255, 79.09131900829608, 79.1795...","[[0.016666666666666666, 0.05, 0.08333333333333...",34.663963,None,NaN,47,1
15,15,"[0.016666666666666666, 0.05, 0.083333333333333...","[40.28146674496771, 60.98417162894271, 47.9096...","[18.139266040545813, 26.341236916957907, 22.03...","[3.2579083557562525, 7.942181760673404, 5.8882...","[59.780078438851895, 59.82056868240072, 59.901...","[[0.016666666666666666, 0.05, 0.08333333333333...",26.340637,None,NaN,26,1
16,16,"[0.016666666666666666, 0.05, 0.083333333333333...","[45.94190619079217, 59.37810797349182, 36.2376...","[21.333326042368782, 33.400573132504164, 17.57...","[5.174091565789792, 12.624230022233089, 6.6445...","[58.78265089658036, 58.829047215862424, 58.919...","[[0.016666666666666666, 0.05, 0.08333333333333...",32.827210,None,NaN,16,-1
17,17,"[0.016666666666666666, 0.05, 0.083333333333333...","[53.93646267489392, 85.99282377174244, 36.2090...","[12.093657959852353, 13.357452090326518, 0.0, ...","[5.408448258972256, 9.445144952444304, 0.0, 0....","[55.299399667426805, 55.31630498622234, 55.163...","[[0.016666666666666666], [0.016666666666666666...",NaN,None,NaN,3,-1
18,18,None,None,None,None,None,None,NaN,None,NaN,0,-1
19,19,None,None,None,None,None,None,NaN,None,NaN,0,-1
20,20,None,None,None,None,None,None,NaN,None,NaN,0,-1
21,21,None,None,None,None,None,None,NaN,None,NaN,0,-1
22,22,None,None,None,None,None,None,NaN,None,NaN,0,-1
23,23,None,None,None,None,None,None,NaN,None,NaN,0,-1
24,24,None,None,None,None,None,None,NaN,None,NaN,0,-1
25,25,None,None,None,None,None,None,NaN,None,NaN,0,-1
26,26,None,None,None,None,None,None,NaN,None,NaN,0,-1
27,27,None,None,None,None,None,None,NaN,None,NaN,0,-1
28,28,None,None,None,None,None,None,NaN,None,NaN,0,-1
29,29,None,None,None,None,None,None,NaN,None,NaN,0,-1
30,30,None,None,None,None,None,None,NaN,None,NaN,0,-1
31,31,None,None,None,None,None,None,NaN,None,NaN,0,-1
32,32,None,None,None,None,None,None,NaN,None,NaN,0,-1
33,33,None,None,None,None,None,None,NaN,None,NaN,0,-1
34,34,None,None,None,None,None,None,NaN,None,NaN,0,-1
35,35,None,None,None,None,None,None,NaN,None,NaN,0,-1
36,36,None,None,None,None,None,None,NaN,None,NaN,0,-1
37,37,None,None,None,None,None,None,NaN,None,NaN,0,-1
38,38,None,None,None,None,None,None,NaN,None,NaN,0,-1
39,39,None,None,None,None,None,None,NaN,None,NaN,0,-1