In [9]:
from transcription_pipeline.RateExtraction import AverageAndFit
import pandas as pd
import matplotlib as mpl
mpl.use('TkAgg')

In [10]:
dataset_folder = '/mnt/Data1/Nick/transcription_pipeline/'
key = '001'

embryo_list = {
    '001': [
        'test_data/NSPARC/2025-08-29/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        # 'test_data/NSPARC/2025-08-29/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo02',
        'test_data/NSPARC/2025-09-02/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        'test_data/NSPARC/2025-09-09/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        'test_data/NSPARC/2025-09-12/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        'test_data/NSPARC/2025-10-23/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        'test_data/NSPARC/2025-10-22/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        # 'test_data/NSPARC/2025-10-22/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo02', # Tracking error
        'test_data/NSPARC/2025-10-24/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01',
        'test_data/NSPARC/2025-10-24/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo02',

    ],

    '002': [
        # 'test_data/NSPARC/2025-08-28/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo01',
        # 'test_data/NSPARC/2025-08-28/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo02',
        'test_data/NSPARC/2025-08-28/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo03',
        'test_data/NSPARC/2025-09-12/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo01',
        'test_data/NSPARC/2025-09-12/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo02',
        'test_data/NSPARC/2025-09-19/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo02',
        'test_data/NSPARC/2025-09-19/MCP-mSG_His-RFP_RBS(002)(trans-het)_embryo03',
    ],

    '003': [
        'test_data/NSPARC/2025-08-28/MCP-mSG_His-RFP_RBS(003)(trans-het)_embryo01',
        'test_data/NSPARC/2025-09-02/MCP-mSG_His-RFP_RBS(003)(trans-het)_embryo01',
        # 'test_data/NSPARC/2025-09-02/MCP-mSG_His-RFP_RBS(003)(trans-het)_embryo02', # Low background
        # 'test_data/NSPARC/2025-09-02/MCP-mSG_His-RFP_RBS(003)(trans-het)_embryo03', # Low background
        'test_data/NSPARC/2025-09-09/MCP-mSG_His-RFP_RBS(003)(trans-het)_embryo01',
        'test_data/NSPARC/2025-09-09/MCP-mSG_His-RFP_RBS(003)(trans-het)_embryo02',
    ],

    '010': [
        'test_data/NSPARC/2025-10-01/MCP-mSG_His-RFP_RBS(010)(trans-het)_embryo01',
        'test_data/NSPARC/2025-10-01/MCP-mSG_His-RFP_RBS(010)(trans-het)_embryo02',
    ]
}
test_dataset_name = dataset_folder + embryo_list[key][0]
print('Dataset Path: ' + test_dataset_name)

Dataset Path: /mnt/Data1/Nick/transcription_pipeline/test_data/NSPARC/2025-08-29/MCP-mSG_His-RFP_RBS(001)(trans-het)_embryo01

In [11]:
# Specify here at what frame NC14 starts
nc14_start_frame = 0

# Width of averaging window for time bins
time_bin_width = 2

# Number of bins you want to split the full embryo into
num_bins = 40

# Load in compiled dataframe
dataframe_path = test_dataset_name + '/compiled_dataframe.pkl'
compiled_dataframe = pd.read_pickle(dataframe_path)

In [12]:
compiled_dataframe.head()

,particle,frame,t_s,intensity_from_neighborhood,intensity_std_error_from_neighborhood,x,y,ap,ap90
0,1,"[118, 120, 121, 122, 123, 124, 126, 127, 128, ...","[243.26393185000123, 247.30997484999895, 249.3...","[200.81261290322587, 167.33742182890856, 226.9...","[69.3905834108402, 65.91025874306226, 62.91598...","[360.8588652713077, 361.26121301028525, 361.80...","[177.24815806136394, 175.93295007808342, 176.5...","[0.2260158551769591, 0.2261460617086001, 0.226...","[0.05705443845780004, 0.05505139323367422, 0.0..."
1,2,"[339, 342, 348, 353]","[689.107527850002, 695.1764588499964, 707.3144...","[238.7377606557377, 501.9694525139665, 354.357...","[63.84332781012953, 59.85447513058666, 66.6523...","[156.48940874412358, 155.56646184002915, 157.0...","[187.42359040166744, 188.28689261978442, 189.1...","[0.13920940639414026, 0.13884306174149336, 0.1...","[0.09464215653647205, 0.0960292723106233, 0.09..."
2,3,[353],[717.4295578500032],[257.52760162601624],[70.20907204130066],[257.76433158064964],[222.90654113071267],[0.18349941086572302],[0.13637446059405858]
3,4,"[85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 9...","[175.7868408499956, 179.8328558499962, 182.029...","[116.11401133144479, 85.42408695652173, 347.91...","[66.39366170776455, 64.70204140531845, 64.4339...","[374.2768465511289, 373.80807534291836, 373.17...","[51.55070640200485, 52.40670043121735, 52.4932...","[0.22778701559278963, 0.22761406407666654, 0.2...","[-0.13163323183723616, -0.13030685293407782, -..."
4,5,"[66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 7...","[137.52390784999727, 139.7208858499974, 141.74...","[205.9754712990936, 210.8030549132948, 249.780...","[65.5110630005391, 62.1747593165315, 66.048325...","[312.34300483235336, 312.7803208422619, 312.83...","[73.07390830532957, 72.30890326621413, 72.3937...","[0.20205979026506246, 0.20222219058429808, 0.2...","[-0.09277830434746978, -0.09396571082974293, -..."

In [13]:
aafdata = AverageAndFit(compiled_dataframe, nc14_start_frame, time_bin_width, num_bins, test_dataset_name, shift_traces=False, min_spots_per_time_bin=5)

Load previous bin fit checking results from "bin_fits_checked.pkl"

In [14]:
aafdata.bin_average_fit_dataframe

,index,time_bin_centers,time_bin_means,time_bin_stddevs,time_bin_stderrs,denoised_time_bin_means,bin_fit_result,bin_fit_slope,bin_fit_result_modified,bin_fit_slope_modified,bin_particle_number,approval_status
0,0,None,None,None,None,None,None,NaN,None,NaN,0,-1
1,1,None,None,None,None,None,None,NaN,None,NaN,0,-1
2,2,"[1.3853287974998354, 1.4186621308331688, 1.451...","[163.08268196721312, 149.99768322981367, 60.36...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8421709430404...","[49.32738076440783, 51.126782256359185, 50.263...","[174.10547783324287, 174.69899623040195, 175.9...","[[1.3853287974998354, 1.4186621308331688, 1.45...",171.285019,None,NaN,8,1
3,3,"[0.97202991416653, 1.0053632474998633, 1.03869...","[238.59077777777776, 115.52998337950139, 369.3...","[2.842170943040401e-14, 0.0, 247.9243792147685...","[55.273657003784514, 52.7279142670789, 38.7494...","[206.21945947080522, 206.41087653154443, 206.1...","[[0.97202991416653], [0.97202991416653, 0.9720...",NaN,"[[1.2053632474998632, 1.2386965808331964, 1.27...",116.500240,37,2
4,4,"[0.9513628641664982, 1.0180295308331648, 1.051...","[223.45368292682926, 492.37605464480873, 73.12...","[0.0, 0.0, 0.0, 114.74167176966816, 73.2792226...","[57.600613953436316, 52.41639148787439, 56.721...","[246.0219124127178, 245.7259604568262, 246.490...","[[0.9513628641664982], [0.9513628641664982, 0....",NaN,"[[1.618029530833165, 1.6513628641664981, 1.684...",101.539951,42,2
5,5,"[0.9600627808332443, 0.9933961141665776, 1.026...","[285.0446188850958, 239.36289116565638, 385.49...","[79.73209438429036, 12.071886593506324, 0.0, 1...","[45.39397103752675, 44.944797183295364, 65.117...","[352.8969514209344, 353.08610634841733, 353.50...","[[3.093396114166578, 3.126729447499911, 3.1600...",110.382124,None,NaN,31,1
6,6,"[1.1743299641666314, 1.2743299641666315, 1.307...","[123.38515662650605, 35.065328313253005, 181.9...","[0.0, 0.0, 107.59375890607153, 0.0, 0.0, 0.0, ...","[60.67738296759387, 64.50498013070327, 43.4770...","[172.69008121877985, 173.09597619883277, 174.0...","[[1.1743299641666314, 1.2743299641666315, 1.30...",110.834824,None,NaN,47,1
7,7,"[1.328045747499913, 1.528045747499913, 1.56137...","[117.22765765765766, 154.21543016759776, 78.97...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 50.9621611...","[62.013106408036705, 61.92018335496028, 67.566...","[146.39599915422127, 146.80692289319498, 147.6...","[[1.528045747499913, 1.5613790808332462, 1.594...",99.219478,None,NaN,55,1
8,8,"[0.914745280833294, 1.8147452808332938, 1.9147...","[485.93250134048264, 116.57033423913043, 201.6...","[0.0, 0.0, 0.0, 0.0, 2.842170943040401e-14, 0....","[63.64896401614412, 65.17255177026767, 66.5084...","[237.19121636685017, 236.91094559898613, 235.8...","[[2.2147452808332937], [2.2147452808332937, 2....",16.789344,"[[1.8147452808332938, 1.9147452808332939, 1.98...",126.150277,33,2
9,9,"[1.2548120808333159, 1.9881454141666492, 2.021...","[195.52510223642176, 149.60803921568626, 172.5...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.8986502399473717, ...","[75.65716927186365, 66.38254879315254, 63.2599...","[252.01154192787587, 252.2954600693018, 252.92...","[[1.9881454141666492, 2.0214787474999825, 2.05...",110.520608,None,NaN,31,1
10,10,"[2.4715145308333137, 2.5048478641666474, 2.604...","[214.69253002610967, 120.26191532961462, 185.7...","[0.0, 126.6688380724943, 0.0, 31.8220699329522...","[62.09586609726107, 45.51047056352435, 62.4581...","[207.5991191995581, 208.0396304509138, 208.992...","[[2.4715145308333137, 2.5048478641666474, 2.60...",83.740730,None,NaN,38,1
11,11,"[1.1507621308331688, 2.4174287974998356, 2.450...","[496.456552631579, 107.94982142857144, 53.0573...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[64.15439815608428, 67.02504840223898, 67.4550...","[176.36672821273072, 176.02344603153392, 175.4...",[],NaN,"[[2.8174287974998355, 2.8507621308331688, 2.91...",146.923010,42,2
12,12,"[0.9821791308333476, 1.2821791308333477, 1.682...","[577.6471235294117, 334.77968965517243, 340.80...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 62.0422583...","[69.96718411393432, 68.76174780769009, 72.6638...","[270.08432885181554, 269.9608372105909, 269.71...","[[2.9155124641666808, 2.982179130833347], [2.9...",1403.053000,"[[3.015512464166681, 3.048845797500014, 3.1155...",84.699099,40,2
13,13,"[1.0496130808333557, 2.416279747500022, 2.8162...","[673.7639583333332, 352.9345311572701, 255.695...","[0.0, 0.0, 0.0, 2.842170943040401e-14, 0.0, 0....","[66.6395762283505, 70.33759181746812, 64.89737...","[282.0110267215531, 281.606156488364, 280.7749...","[[1.0496130808333557, 2.416279747500022, 2.816...",NaN,"[[3.2162797475000224, 3.282946414166689, 3.349...",125.776844,30,2
14,14,"[1.4542126308331889, 1.487545964166522, 1.8208...","[377.10575401069514, 446.5738345864662, 441.39...","[0.0, 0.0, 5.684341886080802e-14, 0.0, 0.0, 0....","[71.83037246706307, 66.17762274384509, 68.6998...","[308.4485579620322, 307.0411151523279, 303.844...","[[1.4542126308331889, 1.487545964166522, 1.820...",NaN,"[[4.520879297499856, 4.554212630833189, 4.5875...",109.327313,32,2
15,15,"[0.9513628641664982, 1.2513628641664982, 3.851...","[35.47975572519084, 413.44255091383815, 110.27...","[0.0, 0.0, 22.04276400011662, 0.0, 0.0, 0.0, 0...","[49.817154937887324, 65.9884364110898, 48.2530...","[193.94277700926105, 194.2962503072077, 194.86...",[],NaN,"[[4.018029530833164, 4.051362864166498, 4.0846...",74.496370,17,2
16,16,"[1.2181963474998871, 1.4515296808332205, 1.918...","[643.8943684210526, 516.2188101265823, 520.681...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[61.78694618406162, 68.08170172396184, 67.8207...","[336.3927767447344, 335.1723848519921, 332.035...",[],NaN,None,NaN,15,-1
17,17,"[1.2519134974998734, 1.5852468308332066, 3.118...","[555.8892021563342, 541.0937352112676, 325.622...","[1.1368683772161603e-13, 0.0, 0.0, 0.0, 0.0, 0...","[65.64973011240039, 62.67028358019143, 68.6303...","[342.6991065113215, 340.322417523695, 334.3387...","[[4.01858016416654, 4.051913497499873], [4.018...",1301.894502,None,NaN,18,0
18,18,"[1.4204974641665815, 1.953830797499915, 2.3871...","[626.64365625, 513.563484375, 454.446494318181...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.6843418860808...","[58.37074869582815, 65.09368860713131, 62.9883...","[450.41415819330695, 447.94687455106884, 442.7...",None,NaN,None,NaN,10,-1
19,19,None,None,None,None,None,None,NaN,None,NaN,0,-1
20,20,None,None,None,None,None,None,NaN,None,NaN,0,-1
21,21,None,None,None,None,None,None,NaN,None,NaN,0,-1
22,22,None,None,None,None,None,None,NaN,None,NaN,0,-1
23,23,None,None,None,None,None,None,NaN,None,NaN,0,-1
24,24,None,None,None,None,None,None,NaN,None,NaN,0,-1
25,25,None,None,None,None,None,None,NaN,None,NaN,0,-1
26,26,None,None,None,None,None,None,NaN,None,NaN,0,-1
27,27,None,None,None,None,None,None,NaN,None,NaN,0,-1
28,28,None,None,None,None,None,None,NaN,None,NaN,0,-1
29,29,None,None,None,None,None,None,NaN,None,NaN,0,-1
30,30,None,None,None,None,None,None,NaN,None,NaN,0,-1
31,31,None,None,None,None,None,None,NaN,None,NaN,0,-1
32,32,None,None,None,None,None,None,NaN,None,NaN,0,-1
33,33,None,None,None,None,None,None,NaN,None,NaN,0,-1
34,34,None,None,None,None,None,None,NaN,None,NaN,0,-1
35,35,None,None,None,None,None,None,NaN,None,NaN,0,-1
36,36,None,None,None,None,None,None,NaN,None,NaN,0,-1
37,37,None,None,None,None,None,None,NaN,None,NaN,0,-1
38,38,None,None,None,None,None,None,NaN,None,NaN,0,-1
39,39,None,None,None,None,None,None,NaN,None,NaN,0,-1

In [15]:
mpl.use('TkAgg')
aafdata.check_bin_fits()

Moved to bin 18 out of 40, the first unchecked bin

In [ ]:
aafdata.save_checked_bin_fits()

In [ ]:
aaf_ap, aaf_slope, aaf_slope_err = aafdata.plot_bin_fits()

In [ ]:
aaf_slope

In [ ]:
# Load checked particle fits
fits_path = test_dataset_name + '/bin_fits_checked.pkl'
bin_fits_checked = pd.read_pickle(fits_path)

In [ ]:
bin_fits_checked

In [ ]:
print(bin_fits_checked['bin_fit_result_modified'][6])

In [ ]:
print(bin_fits_checked['bin_fit_slope'])